import { describe, expect, test } from 'vitest';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Drift guard for the vendored Cezar harness and generic skill tree (spec
 * .ai/specs/2026-07-24-vendored-cez-skills.md). vendor/skills/ is GENERATED
 * by scripts/vendor-skills.mjs from a pinned open-mercato/skills commit —
 * never edited by hand. These tests pin the invariants the harness driver
 * and materializer rely on; when they fail, rerun the vendor script instead
 * of patching files.
 */

const VENDOR = join(import.meta.dirname, '..', 'vendor', 'skills');
const manifest = JSON.parse(readFileSync(join(VENDOR, 'MANIFEST.json'), 'utf8')) as {
  source: { repo: string; ref: string; commit: string };
  nameMap: Record<string, string>;
  requires: Record<string, string[]>;
  cezarOwned: string[];
  skills: string[];
};

describe('vendored Cezar skills (generated by scripts/vendor-skills.mjs)', () => {
  test('manifest pins the upstream source commit and includes every complete generic phase skill', () => {
    expect(manifest.source.repo).toBe('open-mercato/skills');
    expect(manifest.source.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(manifest.skills).toEqual([
      'cez-code-review',
      'cez-fix',
      'cez-harness',
      'cez-implement-spec',
      'cez-pre-implement-spec',
      'cez-root-cause',
      'cez-setup-harness',
      'cez-spec-writing',
      'cez-verify-in-repo',
    ]);
    for (const phaseSkill of [
      'cez-spec-writing',
      'cez-pre-implement-spec',
      'cez-implement-spec',
      'cez-code-review',
      'cez-verify-in-repo',
      'cez-root-cause',
      'cez-fix',
    ]) {
      const skill = readFileSync(join(VENDOR, phaseSkill, 'SKILL.md'), 'utf8');
      expect(skill.length).toBeGreaterThan(3_000);
    }
  });

  test('cezar-authored skills are declared and survive regeneration', () => {
    expect(manifest.cezarOwned).toEqual([
      'cez-setup-harness',
      'cez-pre-implement-spec',
      'cez-implement-spec',
    ]);
    const script = readFileSync(join(VENDOR, '..', '..', '..', '..', 'scripts', 'vendor-skills.mjs'), 'utf8');
    for (const name of manifest.cezarOwned) {
      expect(manifest.skills).toContain(name);
      expect(script).toContain(name);
    }
    expect(script).toMatch(/CEZAR_OWNED\.has\(to\)\) continue/);
  });

  test('the harness runtime selects the complete review contract for the active profile', () => {
    const runtime = join(VENDOR, 'cez-harness', 'scripts', 'harness.mjs');
    expect(existsSync(runtime)).toBe(true);
    const text = readFileSync(runtime, 'utf8');
    expect(text).toContain(
      "const CODE_REVIEW_SKILL = process.env.CEZ_HARNESS_REVIEW_SKILL || 'cez-code-review'",
    );
    expect(text).toContain('`../../${CODE_REVIEW_SKILL}/SKILL.md`');
    expect(text).toContain('`../../${CODE_REVIEW_SKILL}/references/review-checklist.md`');
    expect(text).toContain('`../../${CODE_REVIEW_SKILL}/references/output-format.md`');
    expect(text).toContain('name: CODE_REVIEW_SKILL');
    expect(text).toContain('OM_HARNESS_MODEL');
  });

  test('every vendored skill declares its cez name and has no stale mapped token', () => {
    for (const name of manifest.skills) {
      const skillMd = readFileSync(join(VENDOR, name, 'SKILL.md'), 'utf8');
      expect(skillMd).toContain(`name: ${name}`);
      for (const from of Object.keys(manifest.nameMap)) {
        expect(skillMd).not.toMatch(new RegExp(`${from}(?![a-z0-9-])`));
      }
    }
  });

  test('generic phase playbooks contain no Open Mercato pipeline instructions', () => {
    for (const name of [
      'cez-spec-writing',
      'cez-pre-implement-spec',
      'cez-implement-spec',
      'cez-code-review',
      'cez-verify-in-repo',
      'cez-root-cause',
      'cez-fix',
    ]) {
      const skillRoot = join(VENDOR, name);
      const visit = (dir: string): void => {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          const path = join(dir, entry.name);
          if (entry.isDirectory()) {
            visit(path);
          } else if (entry.name.endsWith('.md')) {
            const text = readFileSync(path, 'utf8');
            expect(text).not.toMatch(/\bom-[a-z0-9-]+/);
            expect(text).not.toMatch(
              /tracker operation|claim the issue|label mutation|claim comment/i,
            );
          }
        }
      };
      visit(skillRoot);
    }
  });

  test('requires closure covers only the Cezar setup wrapper', () => {
    expect(manifest.requires['cez-setup-harness']).toEqual(['cez-harness']);
    expect(manifest.requires['cez-harness']).toBeUndefined();
    const setupMd = readFileSync(join(VENDOR, 'cez-setup-harness', 'SKILL.md'), 'utf8');
    expect(setupMd).toContain('requires: [cez-harness]');
    expect(setupMd).not.toMatch(/run that setup skill first/);
  });
});
