import { createHash } from 'node:crypto';
import { parse } from 'dotenv';
import { z } from 'zod';
import { trackerCredentialsSchema } from '@open-mercato/cezar-contract';

export const connectionRecordSchema = z.object({ id: z.uuid(), projectRoot: z.string().min(1), credentials: trackerCredentialsSchema }).strict();
export type StoredTrackerConnection = z.infer<typeof connectionRecordSchema>;

const digest = (record: StoredTrackerConnection) => {
  const c = record.credentials;
  return createHash('sha256').update(JSON.stringify(c.kind === 'jira'
    ? ['jira', new URL(c.origin).origin, c.email, c.token] : ['linear', c.key])).digest('hex');
};

/** Data only: no process.env writes, interpolation, shell execution, or parser debug logging. */
export function decodeConnectionEnv(text: string): StoredTrackerConnection {
  const values: Record<string, string> = Object.create(null) as Record<string, string>;
  for (const line of text.split(/\r?\n/)) {
    if (!line.trim() || line.trimStart().startsWith('#')) continue;
    const match = /^([A-Z][A-Z0-9_]*)=(.*)$/.exec(line);
    if (!match || Object.hasOwn(values, match[1]!)) throw new Error('Invalid connection file');
    const parsed = parse(line);
    if (!Object.hasOwn(parsed, match[1]!)) throw new Error('Invalid connection file');
    values[match[1]!] = parsed[match[1]!]!;
  }
  const keys = Object.keys(values).sort().join(',');
  const jira = Object.hasOwn(values, 'JIRA_API_TOKEN');
  const expected = ['RECORD_VERSION', 'CONNECTION_ID', 'PROJECT_ROOT', 'CREDENTIAL_SHA256', ...(jira
    ? ['JIRA_BASE_URL', 'JIRA_EMAIL', 'JIRA_API_TOKEN'] : ['LINEAR_API_KEY'])].sort().join(',');
  if (values.RECORD_VERSION !== '1' || keys !== expected) throw new Error('Invalid connection file');
  const record = connectionRecordSchema.parse({ id: values.CONNECTION_ID, projectRoot: values.PROJECT_ROOT, credentials: jira
    ? { kind: 'jira', origin: values.JIRA_BASE_URL, email: values.JIRA_EMAIL, token: values.JIRA_API_TOKEN }
    : { kind: 'linear', key: values.LINEAR_API_KEY } });
  // Private consistency check, NOT encryption/authentication. Editing only the key must not
  // preserve the public revision and leave an old provider cached. Re-save through Settings.
  if (values.CREDENTIAL_SHA256 !== digest(record)) throw new Error('Connection needs saving again');
  return record;
}

function value(text: string): string {
  if (/[\x00-\x1f\x7f]/.test(text)) throw new Error('Invalid credential characters');
  // dotenv has no universal JSON/shell escaping convention. Pick a literal delimiter and
  // verify a lossless round trip; double quotes interpret backslash-n/backslash-r.
  for (const quote of ["'", '`', '"', '']) {
    if (quote && text.includes(quote)) continue;
    const encoded = `${quote}${text}${quote}`;
    if (parse(`VALUE=${encoded}`).VALUE === text) return encoded;
  }
  throw new Error('Unsupported credential characters');
}

export function encodeConnectionEnv(input: StoredTrackerConnection): string {
  const record = connectionRecordSchema.parse(input);
  const credentials = record.credentials;
  const fields: Record<string, string> = {
    RECORD_VERSION: '1', CONNECTION_ID: record.id, PROJECT_ROOT: record.projectRoot, CREDENTIAL_SHA256: digest(record),
    ...(credentials.kind === 'jira'
      ? { JIRA_BASE_URL: credentials.origin, JIRA_EMAIL: credentials.email, JIRA_API_TOKEN: credentials.token }
      : { LINEAR_API_KEY: credentials.key }),
  };
  const text = '# Managed by cezar. Rotate credentials in project Settings; do not edit this file.\n'
    + Object.entries(fields).map(([key, content]) => `${key}=${value(content)}\n`).join('');
  if (JSON.stringify(decodeConnectionEnv(text)) !== JSON.stringify(record)) throw new Error('Invalid credential encoding');
  return text;
}
