import { describe, it, expect, vi, beforeEach, afterAll } from 'vitest';
import {
  actionAlreadyCommented,
  actionPreviouslyCommented,
  autoCommentTag,
  buildAutoCommentBody,
  type BuildAutoCommentArgs,
} from '@cezar/core';
import type { EffectCall } from '@cezar/core';

const baseMeta = {
  actionName: 'auto-triage',
  triggeredBy: 'manual · run now',
  model: 'claude-sonnet-4-6',
  inputTokens: 1234,
  outputTokens: 187,
};

describe('buildAutoCommentBody', () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-05-16T14:02:03Z'));
  });
  afterAll(() => {
    vi.useRealTimers();
  });

  it('renders declared summary text and the applied-effects list', () => {
    const args: BuildAutoCommentArgs = {
      actionName: 'auto-triage',
      text: 'Classified as a bug with high confidence.',
      effectsApplied: [
        { call: { effect: 'label.add', args: { label: 'bug' } }, summary: 'added label "bug" to #42' },
        { call: { effect: 'set-priority', args: { priority: 'high' } }, summary: 'set priority/high on #42' },
      ],
      meta: baseMeta,
    };
    const body = buildAutoCommentBody(args);

    expect(body).toContain('**Cezar · auto-triage**');
    expect(body).toContain('Classified as a bug with high confidence.');
    expect(body).toContain('*Applied:*');
    expect(body).toContain('- added label "bug" to #42');
    expect(body).toContain('- set priority/high on #42');
    expect(body).toContain('Cezar · auto-triage · manual · run now · claude-sonnet-4-6 · 1,234 in / 187 out · 2026-05-16T14:02:03.000Z');
  });

  it('renders tool-use final-text + applied list (same shape)', () => {
    const args: BuildAutoCommentArgs = {
      actionName: 'security-labeler',
      text: 'I reviewed the report — looks like a potential auth bypass.',
      effectsApplied: [
        { call: { effect: 'label.add', args: { label: 'security' } }, summary: 'added label "security" to #88' },
      ],
      meta: { ...baseMeta, actionName: 'security-labeler' },
    };
    const body = buildAutoCommentBody(args);

    expect(body).toContain('**Cezar · security-labeler**');
    expect(body).toContain('looks like a potential auth bypass');
    expect(body).toContain('*Applied:*');
    expect(body).toContain('- added label "security" to #88');
  });

  it('falls back to an autogenerated sentence when there is no text and no effects', () => {
    const args: BuildAutoCommentArgs = {
      actionName: 'auto-triage',
      text: '',
      effectsApplied: [],
      meta: baseMeta,
    };
    const body = buildAutoCommentBody(args);

    expect(body).toContain('**Cezar · auto-triage**');
    expect(body).toContain('Ran auto-triage — no changes applied.');
    expect(body).not.toContain('*Applied:*');
  });

  it('falls back to an effect-count sentence when text is empty but effects fired', () => {
    const args: BuildAutoCommentArgs = {
      actionName: 'auto-triage',
      text: '',
      effectsApplied: [
        { call: { effect: 'label.add', args: { label: 'bug' } }, summary: 'added label "bug" to #1' },
      ],
      meta: baseMeta,
    };
    const body = buildAutoCommentBody(args);

    expect(body).toContain('Ran auto-triage — applied 1 effect.');
    expect(body).toContain('*Applied:*');
  });
});

describe('actionAlreadyCommented', () => {
  const make = (effect: string): { call: EffectCall; summary: string } => ({
    call: { effect: effect as EffectCall['effect'], args: {} },
    summary: '',
  });

  it('returns true when a comment effect was applied', () => {
    expect(actionAlreadyCommented([make('comment')])).toBe(true);
  });

  it('returns true when link-duplicate fired (it posts a comment internally)', () => {
    expect(actionAlreadyCommented([make('link-duplicate')])).toBe(true);
  });

  it('returns false when only non-comment effects fired', () => {
    expect(actionAlreadyCommented([make('label.add'), make('set-priority'), make('close')])).toBe(false);
  });

  it('returns false on an empty list', () => {
    expect(actionAlreadyCommented([])).toBe(false);
  });
});

describe('actionPreviouslyCommented', () => {
  it('matches a prior run by the action footer/heading tag', () => {
    // A real auto-comment from a prior run embeds the stable tag.
    const prior = buildAutoCommentBody({
      actionName: 'auto-triage',
      text: 'Classified as a bug.',
      effectsApplied: [],
      meta: { actionName: 'auto-triage', model: 'claude-sonnet-4-6' },
    });
    expect(actionPreviouslyCommented('auto-triage', [{ body: prior }])).toBe(true);
  });

  it('returns false when no comment carries the action tag', () => {
    expect(
      actionPreviouslyCommented('auto-triage', [
        { body: 'just a human comment' },
        { body: autoCommentTag('some-other-action') },
      ]),
    ).toBe(false);
  });

  it('returns false on an empty comment list', () => {
    expect(actionPreviouslyCommented('auto-triage', [])).toBe(false);
  });
});
