import { describe, it, expect } from 'vitest';
import {
  actionAlreadyCommented,
  actionPreviouslyCommented,
  autoCommentTag,
  buildAutoCommentBody,
  type BuildAutoCommentArgs,
} from '@cezar/core';
import type { EffectCall } from '@cezar/core';

const baseMeta = {
  actionName: 'auto-triage',
  triggeredBy: 'manual · run now',
  model: 'claude-sonnet-4-6',
  inputTokens: 1234,
  outputTokens: 187,
};

describe('buildAutoCommentBody', () => {
  it('renders one summary line, one line per effect, and the provenance footer', () => {
    const args: BuildAutoCommentArgs = {
      actionName: 'auto-triage',
      text: 'Classified as a bug with high confidence.',
      effectsApplied: [
        {
          call: { effect: 'label.add', args: { label: 'bug' } },
          summary: 'added label "bug" to #42',
        },
        {
          call: { effect: 'set-priority', args: { priority: 'high' } },
          summary: 'set priority/high on #42',
        },
      ],
      meta: baseMeta,
    };
    const body = buildAutoCommentBody(args);

    expect(body).toContain('Classified as a bug with high confidence.');
    expect(body).toContain('- added label "bug" to #42');
    expect(body).toContain('- set priority/high on #42');
    expect(body).toContain('🤖 *Cezar · auto-triage · claude-sonnet-4-6 · 1,234 in / 187 out*');
    // No verbose framing.
    expect(body).not.toContain('**Cezar');
    expect(body).not.toContain('*Applied:*');
  });

  it('keeps only the first line of a multi-line summary', () => {
    const body = buildAutoCommentBody({
      actionName: 'security',
      text: 'Potential auth bypass in the session handler.\n\nLong rambling detail paragraph.',
      effectsApplied: [
        {
          call: { effect: 'label.add', args: { label: 'security' } },
          summary: 'added label "security" to #88',
        },
      ],
      meta: { ...baseMeta, actionName: 'security' },
    });

    expect(body).toContain('Potential auth bypass in the session handler.');
    expect(body).not.toContain('Long rambling detail paragraph.');
    expect(body).toContain('- added label "security" to #88');
  });

  it('falls back to an autogenerated sentence when there is no text and no effects', () => {
    const body = buildAutoCommentBody({
      actionName: 'auto-triage',
      text: '',
      effectsApplied: [],
      meta: baseMeta,
    });

    expect(body).toContain('Ran auto-triage — no changes applied.');
  });

  it('falls back to an effect-count sentence when text is empty but effects fired', () => {
    const body = buildAutoCommentBody({
      actionName: 'auto-triage',
      text: '',
      effectsApplied: [
        {
          call: { effect: 'label.add', args: { label: 'bug' } },
          summary: 'added label "bug" to #1',
        },
      ],
      meta: baseMeta,
    });

    expect(body).toContain('Ran auto-triage — applied 1 effect.');
    expect(body).toContain('- added label "bug" to #1');
  });

  it('omits model/tokens from the footer when absent, keeping the dedupe tag', () => {
    const body = buildAutoCommentBody({
      actionName: 'auto-triage',
      text: 'Done.',
      effectsApplied: [],
      meta: { actionName: 'auto-triage' },
    });

    expect(body).toContain('🤖 *Cezar · auto-triage*');
  });
});

describe('actionAlreadyCommented', () => {
  const make = (effect: string): { call: EffectCall; summary: string } => ({
    call: { effect: effect as EffectCall['effect'], args: {} },
    summary: '',
  });

  it('returns true when a comment effect was applied', () => {
    expect(actionAlreadyCommented([make('comment')])).toBe(true);
  });

  it('returns true when link-duplicate fired (it posts a comment internally)', () => {
    expect(actionAlreadyCommented([make('link-duplicate')])).toBe(true);
  });

  it('returns false when only non-comment effects fired', () => {
    expect(actionAlreadyCommented([make('label.add'), make('set-priority'), make('close')])).toBe(
      false,
    );
  });

  it('returns false on an empty list', () => {
    expect(actionAlreadyCommented([])).toBe(false);
  });
});

describe('actionPreviouslyCommented', () => {
  it('matches a prior run by the stable footer tag', () => {
    // A real auto-comment from a prior run embeds the stable tag.
    const prior = buildAutoCommentBody({
      actionName: 'auto-triage',
      text: 'Classified as a bug.',
      effectsApplied: [],
      meta: { actionName: 'auto-triage', model: 'claude-sonnet-4-6' },
    });
    expect(actionPreviouslyCommented('auto-triage', [{ body: prior }])).toBe(true);
  });

  it('matches a comment from the pre-minimal format (heading + audit footer)', () => {
    const legacy =
      '**Cezar · auto-triage**\n\nClassified.\n\n---\n🤖 *Cezar · auto-triage · manual · claude-sonnet-4-6 · 2026-05-16T14:02:03.000Z*';
    expect(actionPreviouslyCommented('auto-triage', [{ body: legacy }])).toBe(true);
  });

  it('returns false when no comment carries the action tag', () => {
    expect(
      actionPreviouslyCommented('auto-triage', [
        { body: 'just a human comment' },
        { body: autoCommentTag('some-other-action') },
      ]),
    ).toBe(false);
  });

  it('returns false on an empty comment list', () => {
    expect(actionPreviouslyCommented('auto-triage', [])).toBe(false);
  });
});
