import { describe, expect, test } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Drift guard for the vendored cez-* skill tree (spec
 * .ai/specs/2026-07-24-vendored-cez-skills.md). vendor/skills/ is GENERATED
 * by scripts/vendor-skills.mjs from a pinned open-mercato/skills commit —
 * never edited by hand. These tests pin the invariants the harness driver
 * and materializer rely on; when they fail, rerun the vendor script instead
 * of patching files.
 */

const VENDOR = join(import.meta.dirname, '..', 'vendor', 'skills');
const manifest = JSON.parse(readFileSync(join(VENDOR, 'MANIFEST.json'), 'utf8')) as {
  source: { repo: string; ref: string; commit: string };
  nameMap: Record<string, string>;
  requires: Record<string, string[]>;
  /** Authored by cezar, preserved across regeneration — not mirrored upstream. */
  cezarOwned: string[];
  skills: string[];
};

describe('vendored cez-* skills (generated by scripts/vendor-skills.mjs)', () => {
  test('manifest pins the upstream source commit and the full skill set', () => {
    expect(manifest.source.repo).toBe('open-mercato/skills');
    expect(manifest.source.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(manifest.skills).toEqual([
      'cez-code-review',
      'cez-fix',
      'cez-harness',
      'cez-root-cause',
      'cez-setup-harness',
      'cez-setup-pipeline',
      'cez-spec-writing',
      'cez-verify-in-repo',
    ]);
  });

  test('cezar-authored skills are declared and survive regeneration', () => {
    // cezar and open-mercato/skills are separate implementations. Where cezar's
    // product shape diverges, cezar's copy is canonical: the vendor script lifts
    // these aside before the wipe and never copies upstream over them, so
    // `source.commit` says nothing about their contents.
    expect(manifest.cezarOwned).toEqual(['cez-setup-harness']);
    const script = readFileSync(join(VENDOR, '..', '..', 'scripts', 'vendor-skills.mjs'), 'utf8');
    for (const name of manifest.cezarOwned) {
      expect(manifest.skills).toContain(name);
      expect(script).toContain(name);
    }
    expect(script).toMatch(/CEZAR_OWNED\.has\(to\)\) continue/);
  });

  test('the harness runtime and its renamed self-references are on disk', () => {
    const runtime = join(VENDOR, 'cez-harness', 'scripts', 'harness.mjs');
    expect(existsSync(runtime)).toBe(true);
    const text = readFileSync(runtime, 'utf8');
    // harness.mjs resolves the review rubric as a sibling skill directory —
    // the rename must have moved that reference with the directory.
    expect(text).toContain("'../../cez-code-review/SKILL.md'");
    expect(text).not.toMatch(/om-code-review/);
    // The adapter env contract is uppercase and must survive the rename.
    expect(text).toContain('OM_HARNESS_MODEL');
  });

  test('every vendored skill declares its cez name and no stale om token', () => {
    for (const name of manifest.skills) {
      const skillMd = readFileSync(join(VENDOR, name, 'SKILL.md'), 'utf8');
      expect(skillMd).toContain(`name: ${name}`);
      for (const from of Object.keys(manifest.nameMap)) {
        // The vendor map's own boundary rule: a vendored token may only
        // survive as the prefix of a longer, non-vendored name.
        expect(skillMd).not.toMatch(new RegExp(`${from}(?![a-z0-9-])`));
      }
    }
  });

  test('requires closure covers the setup skill and the runtime rubric', () => {
    // Adding a model in cezar needs the runtime, NOT pipeline setup: the om
    // skill opens by routing the user through tracker/label/base-branch config
    // before they may bind a model, which dead-ends a first-run cezar user.
    expect(manifest.requires['cez-setup-harness']).toEqual(['cez-harness']);
    expect(manifest.requires['cez-harness']).toEqual(['cez-code-review']);
    const setupMd = readFileSync(join(VENDOR, 'cez-setup-harness', 'SKILL.md'), 'utf8');
    expect(setupMd).toContain('requires: [cez-harness]');
    expect(setupMd).not.toMatch(/run that setup skill first/);
  });
});
